data:
    test:
        dataset:
            type: captioning.datasets.caption_dataset.InferenceDataset
            args:
                features:
                    wav: data/audiocaps/test/waveform.csv
                transforms:
                    wav: Null
                orig_sr: 32000
                target_sr: 32000
        collate_fn:
            type: captioning.datasets.collate_func.VarLenPadCollate
            args:
                pad_keys: [wav]
        caption: data/audiocaps/test/text.json
        dataloader_args:
            shuffle: False
            batch_size: 1
            num_workers: 4

inference_args:
    sample_method: beam
    beam_size: 3
    max_length: 20

resume: swa.pth

caption_output: predictions/swa_beam3.json

score_output: results/swa_beam3.txt
